site_name: Downscaling di Dalam Ilmu Iklim
site_url: https://github.com/agungbaruna
markdown_extensions:
  - pymdownx.snippets
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - bibtex:
      bib_file: 'referensi.bib'
      cite_style: 'pandoc'
nav:
  - 'Dynamical Downscaling': '1_dyn-downscaling.md'
  - 'Statistical Downscaling': '2_sta-downscaling.md'
theme: 
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js